### PR TITLE
fixed: prefix include path with kodi

### PR DESCRIPTION
**Pull request by notspiff**

### CODE REVIEW

**Comment by Jalle19** [comment]
How could this work before without this prefix?

**Comment by notspiff** [comment]
apparently the include paths on windows includes the kodi/ for some reason. it isnt supposed to, ref all other addons.

**Comment by Jalle19** [comment]
@opdenkamp Could this somehow be affected by your platform lib split or should it be okay to merge?

**Comment by opdenkamp** [comment]
just this one will be changed: `#include "kodi/util/util.h"` to `#include "platform/util/util.h"`
PRs coming in today

**Pull request merged**
