### PR TITLE
Jarvis

### PR DESCRIPTION
**Pull request by relipo**
Hi, I'm Ariel, an R&D engineer from VBox Comm.
I Added support for all VBox Comm product families in the master branch, but this is important this applies also to the Jarvis (v16.0) version, since we have a new product family and we need this addon to recognize the new devices & their versions.
Obviously, this will apply also to the next Kodi versions, so we might as well merge those changes.

### CODE REVIEW

**Comment by Jalle19** [comment]
Can you squash the last two commits together?

**Comment by MartijnKaijser** [comment]
you already pushed the changes to Jarvis branch

**Comment by MartijnKaijser** [comment]
and the changes were already there in master

**Comment by relipo** [comment]
Sorry about that. I'm relatively new at this..

**Pull request closed without merging**
